
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.keywordservice.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.keywordservice.replicaCount }}
{{- if .Values.strategyType }}
  strategy:
    type: "{{ .Values.strategyType }}"
{{- end }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Values.keywordservice.name }}
      version: "current"
  template:
    metadata:
      labels:
        app: {{ .Values.keywordservice.name }}
        version: "current"
    spec:
      imagePullSecrets:
      - name: "{{ .Chart.Name }}-secrets"
      containers:
      - name: "{{ .Chart.Name  }}"
        image: "{{ .Values.keywordservice.image.repository }}"
        imagePullPolicy: "{{ .Values.keywordservice.image.pullPolicy }}"
        ports:
        - containerPort: {{ .Values.keywordservice.service.port}}
